### ISSUE TITLE
[CRITICAL] AttributeError: `importlib.metadata.PackageMetadata.json` does not exist in Python < 3.10

### ISSUE THREAD

**Issue by exhumea** [FHPythonUtils/LicenseCheck#75]
Package version: 2024.1.3

The `importlib.metadata.PackageMetadata.json` attribute, used in `licensecheck.packageinfo._pkgMetadataGet` does not exist in Python < 3.10 (whereas 3.9 and 3.8 are declared as supported versions).

**Comment by FredHappyface** [comment]
Hey thanks for this. I'll revert asap once I'm back at my pc. Probably within the next couple of weeks

**Comment by FredHappyface** [comment]
Fixed in #75 . Thanks again for reporting this!

Tested with py 3.11 and 3.8 - noticed another lower priority bugs too. Apologies for letting this slip through in the first place, I think I should investigate a testing pipeline as whilst I always run pytest locally, I havent got into the swing of running tox!

**Comment by FredHappyface** [comment]
Just a follow-up so this sort of thing can be caught in future!

![image](https://github.com/FHPythonUtils/LicenseCheck/assets/41634689/39ffc8e0-ffb3-4873-bb54-d65c5cd9eccc)
