### ISSUE TITLE
 GPL with linking exception

### ISSUE THREAD

**Issue by RomainBrault** [FHPythonUtils/LicenseCheck#87]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar questions in the project's issue tracker to avoid duplicates.
- [x] I have searched existing issues to see if this question has been asked before.

## Your Question

Shouldn't GPL with linking exception be compatible with other open source licences? 

See https://en.wikipedia.org/wiki/GPL_linking_exception

Example

I import pygit2 from an MIT licence project and it says it is incompatible. The author state the contrary (see https://github.com/libgit2/pygit2/issues/632). Wikipedia back this up.

I'm not a lawyer.

**Comment by FredHappyface** [comment]
This is my understanding - Disclaimer: IANAL (I am not a lawyer)

In the context of Python, where libraries are typically imported dynamically at runtime (similar to dynamic linking), the distinction between static and dynamic linking is less clear-cut than in compiled languages. 

Licensecheck errs on the side of caution when flagging GPL-licensed dependencies, even in Python projects, to prevent accidental license violations. The use of a GPL library in a project with a different license, like MIT, may raise concerns about whether the entire project needs to comply with GPL terms. 

It might be absolutely fine to use a library that is GPL licensed in your project, though I'd suggest consulting with a lawyer to ensure compliance with licensing obligations, especially in commercial or business settings.

In my experience, many companies prefer to avoid GPL libraries altogether due to these complexities, including in python.

Again, this does not constitute legal advice, so please speak with a legal professional for specific guidance.

For now, I do not plan on changing this behaviour, as imo it is right to flag potential violations even if unlikely

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2024.3
