### ISSUE TITLE
Bug: License package not scanning for project package version

### ISSUE THREAD

**Issue by meenapushpa** [FHPythonUtils/LicenseCheck#97]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar issues in the project's issue tracker.
- [x] I have searched closed issues to see if a similar problem was reported
  before.

## Issue Details

The licensecheck library is scanning the latest version from pypi instead of scanning the specific version from pyproject.toml file

### Description

When we ran the licenscecheck against the pyproject.toml file and we have specified versions for the packages. 
But it always scanning the latest version of package instead of specific version in pyproject.toml file

example: In pyproject.toml file, we have mongomock-motor==0.0.19

Scanned version: 
![image](https://github.com/user-attachments/assets/fd7745ad-8f01-4597-a58b-729b8069db3a)

Command used:
licensecheck -u poetry:dev --only-licenses  "APACHE SOFTWARE LICENSE" "BSD LICENSE" "ISC LICENSE (ISCL)" "MIT LICENSE" "MOZILLA PUBLIC LICENSE 2.0 (MPL 2.0)" "PUBLIC DOMAIN" "Python Licence 2.0" --ignore-licenses "MOZILLA PUBLIC LICENSE 2.0 (MPL 2.0)" "THE UNLICENSE (UNLICENSE)" -f json

### Expected Behavior

It should scan specific version of package mentioned in file.

### Actual Behavior

It's not scanning the specific version of package, instead it's scans latest version of package

## System Information

Please provide the following additional information about your system or
environment:

- Operating System (OS): Windows
- OS Version: windows 10 pro
- Browser (if applicable): google chrome
- Browser Version (if applicable):
- Project Version (if applicable):

**Comment by meenapushpa** [comment]
is there any update on this issue @FredHappyface ?

**Comment by FredHappyface** [comment]
Hi,

Thank you for raising this issue! I’ve had a chance to review it, and I believe this request is beyond the intended scope of this package.

Typically, package licenses remain consistent across versions. While there are exceptions, these are relatively uncommon. The primary goal of this package is to serve as a smoke test for license compliance in dependencies, rather than a comprehensive tool for verifying licenses across different versions.

Given this, manually checking licenses for specific versions remains the best approach for scenarios like the one described.

**Comment by meenapushpa** [comment]
Thank   you  for the response, but I  see this package can scan specific versions mentioned in  the  requirements file.  Why can ' t we scan the  version of the  package  in  the  toml file  of the PyProject?
